### ISSUE TITLE
Bring this into the core

### ISSUE THREAD

**Issue by watilde** [nodeschool-ja/how-to-npm-jp#21]
Hey @nodeschool-ja/translators,

Currently, I'm working on bringing this great translation work into the core repository since it's hard to do catch-up the updates in original which are easy to happen in the origin problems written in English. It would be helpful if you could have any interest in supporting the translation work with me together or reviewing my update at the following pull request:
+ https://github.com/workshopper/how-to-npm/pull/79

Thanks.

**Comment by tgfjt** [comment]
Super agree.:)

**Comment by watilde** [comment]
Ok it's done finally!
+ https://github.com/workshopper/how-to-npm
